---
name: Release

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: go-calculator
  IMAGE_TAG: ci-${{ github.sha }}

on:
  push:
    branches:
      - main
  workflow_dispatch:


# GITHUB_TOKEN authentication to sumbit SBOM results to GitHub Dependency Graph
# (necessary since I'm not going to use a PAT)
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: |
          go mod download
          go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run unit tests
        run: go test -v -tags=unit ./...

      - name: Build image with commit hash tag
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Save Docker image as tar file
        run: docker save ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -o ${{ env.IMAGE_NAME }}.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ${{ env.IMAGE_NAME }}.tar

  secure:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load -i ${{ env.IMAGE_NAME }}.tar

      - name: Verify image
        run: docker images

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'image'
          image-ref: '${{ env.IMAGE_NAME }}'
          format: 'table'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

      - name: Generate SBOM and submit results to GitHub Dependency Graph
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'image'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '${{ env.IMAGE_NAME }}'
          github-pat: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: [build, secure]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5

      - name: Run integration tests
        # -count=1 disables test caching to ensure fresh execution with containers/DB state
        # Required because integration tests rely on external systems that change between runs
        run: go test -v -tags=integration ./... -count=1

  release:
    runs-on: ubuntu-latest
    needs: [build, secure, test]
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load -i ${{ env.IMAGE_NAME }}.tar

      - name: Verify image
        run: docker images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Container Registry
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
